import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Nav from '../components/Nav';
import Header from '../components/Header';
import styles from '../styles/Home.module.scss';
import ProductSlider from '../components/ProductSlider';
import axios from 'axios';
import { ProductInterface } from '../types/interfaces';
import { RECOMMENDED } from '../utils/constants';
import SignUpHero from '../components/SignUpHero';
import Layout from '../components/Layout';
import useMobile from '../utils/hooks/useMobile';
import { useEffect } from 'react';

interface Props {
  recommended: ProductInterface[];
}
const Home: NextPage<Props> = ({
  recommended = RECOMMENDED as ProductInterface[],
}) => {
  const { mobileCheck } = useMobile();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav mobile={mobileCheck.current} />
      <Header />
      <Layout mobile={mobileCheck.current}>
        <main className={styles.main}>
          <ProductSlider title="recommended for you" products={recommended} />
          <SignUpHero />
          <ProductSlider
            title="featured sets"
            products={[...recommended].reverse()}
          />
        </main>
      </Layout>
    </div>
  );
};

export default Home;
